services:

  rabbitmq:
    image: "rabbitmq:3-management"
    container_name: "rabbitmq"
    env_file: .env
    ports:
      - "${RABBITMQ_PORT}:5672"
      - "15672:15672"
    volumes:
      - "rabbitmq-data:/var/lib/rabbitmq"

  postgres:
    image: "bitnami/postgresql:latest"
    container_name: "postgres"
    env_file: .env
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - "postgres-data:/var/lib/postgresql/data"

volumes:
  rabbitmq-data:
  postgres-data: