services:

  rabbitmq:
    image: "rabbitmq:3-management"
    container_name: "rabbitmq"
    env_file: .env
    ports:
      - "${RABBITMQ_PORT}:5672"
      - "15672:15672"
    volumes:
      - "rabbitmq-data:/var/lib/rabbitmq"

volumes:
  rabbitmq-data: