// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type IngredientRecipe struct {
	Name   string `json:"name"`
	Amount int    `json:"amount"`
	Unit   string `json:"unit"`
}

type Mutation struct {
}

type NewTodo struct {
	Text   string `json:"text"`
	UserID string `json:"userId"`
}

type Query struct {
}

type Recipe struct {
	ID          string              `json:"id"`
	Name        string              `json:"name"`
	Author      string              `json:"author"`
	Description string              `json:"description"`
	Dish        string              `json:"dish"`
	Servings    int                 `json:"servings"`
	Timers      []*Timer            `json:"timers,omitempty"`
	Steps       []string            `json:"steps"`
	Ingredients []*IngredientRecipe `json:"ingredients"`
}

type Timer struct {
	Name   string `json:"name"`
	Amount int    `json:"amount"`
	Unit   string `json:"unit"`
}

type Todo struct {
	ID   string `json:"id"`
	Text string `json:"text"`
	Done bool   `json:"done"`
	User *User  `json:"user"`
}

type User struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}
